"""Repository for Elastic Security alert entities."""
from __future__ import annotations

from domain.es_alert import EsAlert
from repository.base import Repository


class EsAlertRepository(Repository[EsAlert]):
    """In-memory repository for ``EsAlert`` domain objects."""

    def __init__(self) -> None:
        """Initialise the repository bound to the es_alerts collection."""
        super().__init__("es_alerts")

    def get_by_rule_id(self, rule_id: str) -> list[EsAlert]:
        """Return all alerts generated by the given rule."""
        return [a for a in self.list_all() if a.signal_rule_id == rule_id]



es_alert_repo = EsAlertRepository()
