"""Filters the SentinelOne swagger declares, generated — do not edit by hand.

    backend/.venv/bin/python scripts/gen_documented_filters.py

Each entry is a parameter the vendor documents whose field this mock's own
response carries. The suffix decides the operator; a parameter whose field
we do not have is not here and stays in `scripts/param_drift.py`'s count.
"""

from __future__ import annotations

from utils.filtering import FilterSpec

#: route (without the API prefix) -> the specs derived for it
DOCUMENTED_FILTERS: dict[str, list[FilterSpec]] = {
    "/accounts": [
        FilterSpec("billingMode", "billingMode", "eq", enum=True),
        FilterSpec("createdAt", "createdAt", "eq"),
        FilterSpec("expiration", "expiration", "eq"),
        FilterSpec("isDefault", "isDefault", "bool"),
        FilterSpec("module", "licenses.modules", "eq"),
        FilterSpec("name__contains", "name", "contains"),
        FilterSpec("sku", "skus", "eq"),
        FilterSpec("state", "state", "eq", enum=True),
        FilterSpec("statesNin", "state", "nin"),
        FilterSpec("totalLicenses", "totalLicenses", "eq"),
        FilterSpec("usageType", "usageType", "eq", enum=True),
    ],
    "/activities": [
        FilterSpec("activityUuids", "activityUuid", "in"),
        FilterSpec("createdAt__between", "createdAt", "between"),
        FilterSpec("createdAt__gt", "createdAt", "gt"),
        FilterSpec("createdAt__lt", "createdAt", "lt"),
        FilterSpec("groupIds", "groupId", "in"),
        FilterSpec("threatIds", "threatId", "in"),
    ],
    "/agents": [
        FilterSpec("activeProtection", "activeProtection", "in", enum=True),
        FilterSpec("activeThreats", "activeThreats", "eq"),
        FilterSpec("activeThreats__gt", "activeThreats", "gt"),
        FilterSpec("agentVersion__between", "agentVersion", "between"),
        FilterSpec("agentVersion__gt", "agentVersion", "gt"),
        FilterSpec("agentVersion__gte", "agentVersion", "gte"),
        FilterSpec("agentVersion__lt", "agentVersion", "lt"),
        FilterSpec("agentVersion__lte", "agentVersion", "lte"),
        FilterSpec("agentVersions", "agentVersion", "in"),
        FilterSpec("agentVersionsNin", "agentVersion", "nin"),
        FilterSpec("cloudProvider", "cloudProviders", "in"),
        FilterSpec("cloudProviderNin", "cloudProviders", "nin"),
        FilterSpec("computerName__contains", "computerName", "contains"),
        FilterSpec("console", "proxyStates.console", "in"),
        FilterSpec("containerizedWorkloadCounts", "containerizedWorkloadCounts", "eq"),
        FilterSpec("coreCount__between", "coreCount", "between"),
        FilterSpec("coreCount__gt", "coreCount", "gt"),
        FilterSpec("coreCount__gte", "coreCount", "gte"),
        FilterSpec("coreCount__lt", "coreCount", "lt"),
        FilterSpec("coreCount__lte", "coreCount", "lte"),
        FilterSpec("cpuCount__between", "cpuCount", "between"),
        FilterSpec("cpuCount__gt", "cpuCount", "gt"),
        FilterSpec("cpuCount__gte", "cpuCount", "gte"),
        FilterSpec("cpuCount__lt", "cpuCount", "lt"),
        FilterSpec("cpuCount__lte", "cpuCount", "lte"),
        FilterSpec("cpuId__contains", "cpuId", "contains"),
        FilterSpec("createdAt__between", "createdAt", "between"),
        FilterSpec("createdAt__gt", "createdAt", "gt"),
        FilterSpec("createdAt__gte", "createdAt", "gte"),
        FilterSpec("createdAt__lt", "createdAt", "lt"),
        FilterSpec("createdAt__lte", "createdAt", "lte"),
        FilterSpec("deepVisibility", "proxyStates.deepVisibility", "in"),
        FilterSpec("domains", "domain", "in"),
        FilterSpec("domainsNin", "domain", "nin"),
        FilterSpec("encryptedApplications", "encryptedApplications", "in"),
        FilterSpec("externalId__contains", "externalId", "contains"),
        FilterSpec("externalIp__contains", "externalIp", "contains"),
        FilterSpec("firewallEnabled", "firewallEnabled", "in"),
        FilterSpec("gatewayIp", "networkInterfaces.gatewayIp", "eq"),
        FilterSpec("hasContainerizedWorkload", "hasContainerizedWorkload", "in"),
        FilterSpec("idsNin", "tags.sentinelone.id", "nin"),
        FilterSpec("installerTypes", "installerType", "in", enum=True),
        FilterSpec("installerTypesNin", "installerType", "nin", enum=True),
        FilterSpec("isAdConnector", "isAdConnector", "in"),
        FilterSpec("isHyperAutomate", "isHyperAutomate", "in"),
        FilterSpec("isUninstalled", "isUninstalled", "in"),
        FilterSpec("lastActiveDate__between", "lastActiveDate", "between"),
        FilterSpec("lastActiveDate__gt", "lastActiveDate", "gt"),
        FilterSpec("lastActiveDate__gte", "lastActiveDate", "gte"),
        FilterSpec("lastActiveDate__lt", "lastActiveDate", "lt"),
        FilterSpec("lastActiveDate__lte", "lastActiveDate", "lte"),
        FilterSpec("lastLoggedInUserName__contains", "lastLoggedInUserName", "contains"),
        FilterSpec("lastSuccessfulScanDate__between", "lastSuccessfulScanDate", "between"),
        FilterSpec("lastSuccessfulScanDate__gt", "lastSuccessfulScanDate", "gt"),
        FilterSpec("lastSuccessfulScanDate__gte", "lastSuccessfulScanDate", "gte"),
        FilterSpec("lastSuccessfulScanDate__lt", "lastSuccessfulScanDate", "lt"),
        FilterSpec("lastSuccessfulScanDate__lte", "lastSuccessfulScanDate", "lte"),
        FilterSpec("locationEnabled", "locationEnabled", "in"),
        FilterSpec("machineTypes", "machineType", "in", enum=True),
        FilterSpec("machineTypesNin", "machineType", "nin", enum=True),
        FilterSpec("missingPermissions", "missingPermissions", "in", enum=True),
        FilterSpec("missingPermissionsNin", "missingPermissions", "nin", enum=True),
        FilterSpec("mitigationMode", "mitigationMode", "eq", enum=True),
        FilterSpec("mitigationModeSuspicious", "mitigationModeSuspicious", "eq", enum=True),
        FilterSpec("networkQuarantineEnabled", "networkQuarantineEnabled", "in"),
        FilterSpec("operationalStates", "operationalState", "in"),
        FilterSpec("operationalStatesNin", "operationalState", "nin"),
        FilterSpec("osArch", "osArch", "eq", enum=True),
        FilterSpec("osTypesNin", "osType", "nin", enum=True),
        FilterSpec("pacFileUsage", "proxyStates.pacFileUsage", "in"),
        FilterSpec("proxyMethod", "proxyStates.proxyMethod", "in"),
        FilterSpec("proxyMethodNin", "proxyStates.proxyMethod", "nin"),
        FilterSpec("rangerStatus", "rangerStatus", "eq", enum=True),
        FilterSpec("rangerVersions", "rangerVersion", "in"),
        FilterSpec("rangerVersionsNin", "rangerVersion", "nin"),
        FilterSpec("registeredAt__between", "registeredAt", "between"),
        FilterSpec("registeredAt__gt", "registeredAt", "gt"),
        FilterSpec("registeredAt__lt", "registeredAt", "lt"),
        FilterSpec("remoteProfilingStates", "remoteProfilingState", "in"),
        FilterSpec("remoteProfilingStatesNin", "remoteProfilingState", "nin"),
        FilterSpec("scanStatus", "scanStatus", "eq", enum=True),
        FilterSpec("serialNumber__contains", "serialNumber", "contains"),
        FilterSpec("storageTypes", "storageType", "in"),
        FilterSpec("storageTypesNin", "storageType", "nin"),
        FilterSpec("threatRebootRequired", "threatRebootRequired", "in"),
        FilterSpec("totalMemory__between", "totalMemory", "between"),
        FilterSpec("totalMemory__gt", "totalMemory", "gt"),
        FilterSpec("totalMemory__gte", "totalMemory", "gte"),
        FilterSpec("totalMemory__lt", "totalMemory", "lt"),
        FilterSpec("totalMemory__lte", "totalMemory", "lte"),
        FilterSpec("updatedAt__between", "updatedAt", "between"),
        FilterSpec("updatedAt__gt", "updatedAt", "gt"),
        FilterSpec("updatedAt__lt", "updatedAt", "lt"),
        FilterSpec("updatedAt__lte", "updatedAt", "lte"),
        FilterSpec("userActionsNeeded", "userActionsNeeded", "in", enum=True),
        FilterSpec("userActionsNeededNin", "userActionsNeeded", "nin", enum=True),
        FilterSpec("uuid", "uuid", "eq"),
        FilterSpec("uuid__contains", "uuid", "contains"),
        FilterSpec("uuids", "uuid", "in"),
    ],
    "/agents/passphrases": [
        FilterSpec("computerName", "computerName", "eq"),
        FilterSpec("computerName__contains", "computerName", "contains"),
        FilterSpec("createdAt__between", "createdAt", "between"),
        FilterSpec("createdAt__gt", "createdAt", "gt"),
        FilterSpec("createdAt__gte", "createdAt", "gte"),
        FilterSpec("createdAt__lt", "createdAt", "lt"),
        FilterSpec("createdAt__lte", "createdAt", "lte"),
        FilterSpec("domains", "domain", "in"),
        FilterSpec("domainsNin", "domain", "nin"),
        FilterSpec("idsNin", "id", "nin"),
        FilterSpec("lastLoggedInUserName__contains", "lastLoggedInUserName", "contains"),
        FilterSpec("uuid", "uuid", "eq"),
        FilterSpec("uuid__contains", "uuid", "contains"),
        FilterSpec("uuids", "uuid", "in"),
    ],
    "/agents/tags": [
        FilterSpec("createdBy", "createdBy", "eq"),
        FilterSpec("updatedBy", "updatedBy", "eq"),
    ],
    "/cloud-detection/alerts": [
        FilterSpec("createdAt__gt", "alertInfo.createdAt", "gt"),
        FilterSpec("createdAt__lt", "alertInfo.createdAt", "lt"),
        FilterSpec("machineType", "agentDetectionInfo.machineType", "in"),
        FilterSpec("reportedAt__gt", "alertInfo.reportedAt", "gt"),
        FilterSpec("reportedAt__gte", "alertInfo.reportedAt", "gte"),
        FilterSpec("reportedAt__lt", "alertInfo.reportedAt", "lt"),
        FilterSpec("reportedAt__lte", "alertInfo.reportedAt", "lte"),
    ],
    "/cloud-detection/rules": [
        FilterSpec("accountIds", "accountId", "in"),
        FilterSpec("activeResponse", "activeResponse", "bool"),
        FilterSpec("creator__contains", "enrichment.creator", "contains"),
        FilterSpec("description__contains", "description", "contains"),
        FilterSpec("expirationMode", "expirationMode", "eq", enum=True),
        FilterSpec("expired", "expired", "bool"),
        FilterSpec("name__contains", "name", "contains"),
        FilterSpec("reachedLimit", "reachedLimit", "bool"),
        FilterSpec("s1ql__contains", "s1ql", "contains"),
        FilterSpec("scopeId", "scopeId", "eq"),
        FilterSpec("scopes", "scope", "in", enum=True),
        FilterSpec("siteIds", "siteId", "in"),
    ],
    "/device-control": [
        FilterSpec("accessPermissions", "accessPermission", "in", enum=True),
        FilterSpec("createdAt__between", "createdAt", "between"),
        FilterSpec("createdAt__gt", "createdAt", "gt"),
        FilterSpec("createdAt__gte", "createdAt", "gte"),
        FilterSpec("createdAt__lt", "createdAt", "lt"),
        FilterSpec("createdAt__lte", "createdAt", "lte"),
        FilterSpec("deviceIds", "deviceId", "in"),
        FilterSpec("deviceInformationServiceInfoKeys", "deviceInformationServiceInfoKey", "in"),
        FilterSpec("deviceNames", "deviceName", "in"),
        FilterSpec("gattServices", "gattService", "in"),
        FilterSpec("interfaces", "interface", "in", enum=True),
        FilterSpec("manufacturerNames", "manufacturerName", "in"),
        FilterSpec("minorClasses", "minorClasses", "in"),
        FilterSpec("productIds", "productId", "in"),
        FilterSpec("ruleName", "ruleName", "eq"),
        FilterSpec("scopes", "scope", "in", enum=True),
        FilterSpec("uids", "uid", "in"),
        FilterSpec("vendorIds", "vendorId", "in"),
        FilterSpec("versions", "version", "in"),
    ],
    "/exclusions": [
        FilterSpec("accountIds", "scope.accountIds", "in"),
        FilterSpec("applicationName__contains", "applicationName", "contains"),
        FilterSpec("createdAt__between", "createdAt", "between"),
        FilterSpec("createdAt__gt", "createdAt", "gt"),
        FilterSpec("createdAt__gte", "createdAt", "gte"),
        FilterSpec("createdAt__lt", "createdAt", "lt"),
        FilterSpec("createdAt__lte", "createdAt", "lte"),
        FilterSpec("description__contains", "description", "contains"),
        FilterSpec("groupIds", "scope.groupIds", "in"),
        FilterSpec("imported", "imported", "in"),
        FilterSpec("inAppInventory", "inAppInventory", "bool"),
        FilterSpec("modes", "mode", "in", enum=True),
        FilterSpec("notRecommended", "notRecommended", "in", enum=True),
        FilterSpec("pathExclusionTypes", "pathExclusionType", "in", enum=True),
        FilterSpec("scopePath__contains", "scopePath", "contains"),
        FilterSpec("source", "source", "in", enum=True),
        FilterSpec("updatedAt__between", "updatedAt", "between"),
        FilterSpec("updatedAt__gt", "updatedAt", "gt"),
        FilterSpec("updatedAt__gte", "updatedAt", "gte"),
        FilterSpec("updatedAt__lt", "updatedAt", "lt"),
        FilterSpec("updatedAt__lte", "updatedAt", "lte"),
        FilterSpec("userIds", "userId", "in"),
        FilterSpec("value", "value", "eq"),
    ],
    "/firewall-control": [
        FilterSpec("application__contains", "application", "contains"),
        FilterSpec("applications", "application", "in"),
        FilterSpec("createdAt__between", "createdAt", "between"),
        FilterSpec("createdAt__gt", "createdAt", "gt"),
        FilterSpec("createdAt__gte", "createdAt", "gte"),
        FilterSpec("createdAt__lt", "createdAt", "lt"),
        FilterSpec("createdAt__lte", "createdAt", "lte"),
        FilterSpec("directions", "direction", "in", enum=True),
        FilterSpec("name", "name", "eq"),
        FilterSpec("name__contains", "name", "contains"),
        FilterSpec("osTypes", "osTypes", "in", enum=True),
        FilterSpec("protocol__contains", "protocol", "contains"),
        FilterSpec("protocols", "protocol", "in"),
        FilterSpec("scopes", "scope", "in", enum=True),
        FilterSpec("tagIds", "tagIds", "in"),
        FilterSpec("tagName__contains", "tagNames", "contains"),
    ],
    "/groups": [
        FilterSpec("description", "description", "eq"),
        FilterSpec("isDefault", "isDefault", "bool"),
        FilterSpec("rank", "rank", "eq"),
        FilterSpec("registrationToken", "registrationToken", "eq"),
        FilterSpec("type", "type", "eq", enum=True),
    ],
    "/installed-applications": [
        FilterSpec("agentComputerName__contains", "agentComputerName", "contains"),
        FilterSpec("agentMachineTypes", "agentMachineType", "in", enum=True),
        FilterSpec("agentMachineTypesNin", "agentMachineType", "nin", enum=True),
        FilterSpec("agentUuid__contains", "agentUuid", "contains"),
        FilterSpec("name__contains", "name", "contains"),
        FilterSpec("osTypes", "osType", "in", enum=True),
        FilterSpec("osTypesNin", "osType", "nin", enum=True),
        FilterSpec("publisher__contains", "publisher", "contains"),
        FilterSpec("riskLevels", "riskLevel", "in", enum=True),
        FilterSpec("riskLevelsNin", "riskLevel", "nin", enum=True),
        FilterSpec("size__between", "size", "between"),
        FilterSpec("types", "type", "in", enum=True),
        FilterSpec("typesNin", "type", "nin", enum=True),
        FilterSpec("version__contains", "version", "contains"),
    ],
    "/restrictions": [
        FilterSpec("accountIds", "scope.accountIds", "in"),
        FilterSpec("createdAt__between", "createdAt", "between"),
        FilterSpec("createdAt__gt", "createdAt", "gt"),
        FilterSpec("createdAt__gte", "createdAt", "gte"),
        FilterSpec("createdAt__lt", "createdAt", "lt"),
        FilterSpec("createdAt__lte", "createdAt", "lte"),
        FilterSpec("description__contains", "description", "contains"),
        FilterSpec("groupIds", "scope.groupIds", "in"),
        FilterSpec("imported", "imported", "in"),
        FilterSpec("osTypes", "osType", "in", enum=True),
        FilterSpec("source", "source", "in", enum=True),
        FilterSpec("type", "type", "eq", enum=True),
        FilterSpec("updatedAt__between", "updatedAt", "between"),
        FilterSpec("updatedAt__gt", "updatedAt", "gt"),
        FilterSpec("updatedAt__gte", "updatedAt", "gte"),
        FilterSpec("updatedAt__lt", "updatedAt", "lt"),
        FilterSpec("updatedAt__lte", "updatedAt", "lte"),
        FilterSpec("userIds", "userId", "in"),
        FilterSpec("value", "value", "eq"),
        FilterSpec("value__contains", "value", "contains"),
    ],
    "/sites": [
        FilterSpec("accountId", "accountId", "eq"),
        FilterSpec("accountName__contains", "accountName", "contains"),
        FilterSpec("activeLicenses", "activeLicenses", "eq"),
        FilterSpec("createdAt", "createdAt", "eq"),
        FilterSpec("description", "description", "eq"),
        FilterSpec("description__contains", "description", "contains"),
        FilterSpec("expiration", "expiration", "eq"),
        FilterSpec("healthStatus", "healthStatus", "bool"),
        FilterSpec("isDefault", "isDefault", "bool"),
        FilterSpec("module", "licenses.modules", "eq"),
        FilterSpec("name__contains", "licenses.modules.name", "contains"),
        FilterSpec("registrationToken", "registrationToken", "eq"),
        FilterSpec("siteType", "siteType", "eq", enum=True),
        FilterSpec("sku", "sku", "eq"),
        FilterSpec("state", "state", "eq", enum=True),
        FilterSpec("statesNin", "state", "nin"),
        FilterSpec("suite", "suite", "eq", enum=True),
        FilterSpec("totalLicenses", "totalLicenses", "eq"),
    ],
    "/threat-intelligence/iocs": [
        FilterSpec("batchId", "batchId", "eq"),
        FilterSpec("campaignNames__in", "campaignNames", "in"),
        FilterSpec("category__in", "category", "in"),
        FilterSpec("creationTime__gt", "creationTime", "gt"),
        FilterSpec("creationTime__gte", "creationTime", "gte"),
        FilterSpec("creationTime__lt", "creationTime", "lt"),
        FilterSpec("creationTime__lte", "creationTime", "lte"),
        FilterSpec("creator__contains", "creator", "contains"),
        FilterSpec("description__contains", "description", "contains"),
        FilterSpec("externalId", "externalId", "eq"),
        FilterSpec("labels__in", "labels", "in"),
        FilterSpec("malwareNames__in", "malwareNames", "in"),
        FilterSpec("name__contains", "name", "contains"),
        FilterSpec("severity", "severity", "in"),
        FilterSpec("threatActorTypes__in", "threatActorTypes", "in"),
        FilterSpec("threatActors__in", "threatActors", "in"),
        FilterSpec("updatedAt__gt", "updatedAt", "gt"),
        FilterSpec("updatedAt__gte", "updatedAt", "gte"),
        FilterSpec("updatedAt__lt", "updatedAt", "lt"),
        FilterSpec("updatedAt__lte", "updatedAt", "lte"),
        FilterSpec("uploadTime__gt", "uploadTime", "gt"),
        FilterSpec("uploadTime__gte", "uploadTime", "gte"),
        FilterSpec("uploadTime__lt", "uploadTime", "lt"),
        FilterSpec("uploadTime__lte", "uploadTime", "lte"),
    ],
    "/threats": [
        FilterSpec("agentIsActive", "agentRealtimeInfo.agentIsActive", "bool"),
        FilterSpec("agentMachineTypes", "agentRealtimeInfo.agentMachineType", "in", enum=True),
        FilterSpec("agentMachineTypesNin", "agentRealtimeInfo.agentMachineType", "nin", enum=True),
        FilterSpec("agentVersions", "agentDetectionInfo.agentVersion", "in"),
        FilterSpec("agentVersionsNin", "agentDetectionInfo.agentVersion", "nin"),
        FilterSpec("analystVerdictsNin", "threatInfo.analystVerdict", "nin", enum=True),
        FilterSpec("classificationSources", "threatInfo.classificationSource", "in", enum=True),
        FilterSpec("classificationSourcesNin", "threatInfo.classificationSource", "nin", enum=True),
        FilterSpec("classificationsNin", "threatInfo.classification", "nin"),
        FilterSpec("cloudProvider", "agentDetectionInfo.cloudProviders", "in"),
        FilterSpec("cloudProviderNin", "agentDetectionInfo.cloudProviders", "nin"),
        FilterSpec("collectionIds", "threatInfo.collectionId", "in"),
        FilterSpec("confidenceLevelsNin", "threatInfo.confidenceLevel", "nin", enum=True),
        FilterSpec("createdAt__gt", "threatInfo.createdAt", "gt"),
        FilterSpec("createdAt__lt", "threatInfo.createdAt", "lt"),
        FilterSpec("detectionEngines", "threatInfo.detectionEngines", "in", enum=True),
        FilterSpec("detectionEnginesNin", "threatInfo.detectionEngines", "nin", enum=True),
        FilterSpec("engines", "threatInfo.engines", "in", enum=True),
        FilterSpec("enginesNin", "threatInfo.engines", "nin", enum=True),
        FilterSpec("externalTicketExists", "threatInfo.externalTicketExists", "bool"),
        FilterSpec("externalTicketId__contains", "threatInfo.externalTicketId", "contains"),
        FilterSpec("externalTicketIds", "threatInfo.externalTicketId", "in"),
        FilterSpec("failedActions", "threatInfo.failedActions", "bool"),
        FilterSpec("filePath__contains", "threatInfo.filePath", "contains"),
        FilterSpec("initiatedBy", "threatInfo.initiatedBy", "in", enum=True),
        FilterSpec("initiatedByNin", "threatInfo.initiatedBy", "nin", enum=True),
        FilterSpec("mitigatedPreemptively", "threatInfo.mitigatedPreemptively", "bool"),
        FilterSpec("pendingActions", "threatInfo.pendingActions", "bool"),
        FilterSpec("publisherName__contains", "threatInfo.publisherName", "contains"),
        FilterSpec("rebootRequired", "agentRealtimeInfo.rebootRequired", "bool"),
        FilterSpec("storyline__contains", "threatInfo.storyline", "contains"),
        FilterSpec("storylines", "threatInfo.storyline", "in"),
        FilterSpec("updatedAt__gt", "threatInfo.updatedAt", "gt"),
        FilterSpec("updatedAt__gte", "threatInfo.updatedAt", "gte"),
        FilterSpec("updatedAt__lt", "threatInfo.updatedAt", "lt"),
        FilterSpec("updatedAt__lte", "threatInfo.updatedAt", "lte"),
    ],
    "/users": [
        FilterSpec("canGenerateApiToken", "canGenerateApiToken", "bool"),
        FilterSpec("dateJoined", "dateJoined", "eq"),
        FilterSpec("emailReadOnly", "emailReadOnly", "bool"),
        FilterSpec("emailVerified", "emailVerified", "bool"),
        FilterSpec("email__contains", "email", "contains"),
        FilterSpec("firstLogin", "firstLogin", "eq"),
        FilterSpec("fullName", "fullName", "eq"),
        FilterSpec("fullNameReadOnly", "fullNameReadOnly", "bool"),
        FilterSpec("fullName__contains", "fullName", "contains"),
        FilterSpec("groupsReadOnly", "groupsReadOnly", "bool"),
        FilterSpec("lastLogin", "lastLogin", "eq"),
        FilterSpec("primaryTwoFaMethod", "primaryTwoFaMethod", "eq"),
        FilterSpec("roleIds", "scopeRoles.roleId", "in"),
        FilterSpec("source", "source", "eq", enum=True),
        FilterSpec("sources", "source", "in", enum=True),
        FilterSpec("twoFaEnabled", "twoFaEnabled", "bool"),
        FilterSpec("twoFaStatus", "twoFaStatus", "eq"),
    ],
}
