"""What each SentinelOne write body must carry, from the 2.1 swagger.

Generated by scripts/gen_documented_bodies.py — do not edit by hand.

A route that answers 200 to a body carrying none of these members is
accepting a body the vendor's own reference says is not one. The mock
also takes the flat form of these payloads, so `data`'s own members
count as having been sent too.
"""
from __future__ import annotations

#: ``(method, route path)`` → every member the swagger documents for
#: that body. The path is the one the router carries — no API prefix.
DOCUMENTED_BODIES: dict[tuple[str, str], frozenset[str]] = {
    ("POST", "/accounts"): frozenset({
        "accountType", "billingMode", "data", "expiration", "externalId",
        "inherits", "irFields", "licenses", "makeSocDefaultUi", "name",
        "policy", "skus", "unlimitedExpiration", "usageType"
    }),
    ("PUT", "/accounts/{account_id}"): frozenset({
        "accountType", "billingMode", "data", "expiration", "externalId",
        "inherits", "irFields", "licenses", "makeSocDefaultUi", "name",
        "policy", "salesforceId", "skus", "unlimitedExpiration",
        "usageType"
    }),
    ("PUT", "/accounts/{account_id}/policy"): frozenset({
        "agentLoggingOn", "agentNotification", "agentUi", "agentUiOn",
        "allowRemoteShell", "allowUnprotectByApprovedProcess",
        "antiTamperingOn", "autoDecommissionDays", "autoDecommissionOn",
        "autoFileUpload", "autoImmuneOn", "autoMitigationAction",
        "cloudValidationOn", "createdAt", "data",
        "driftDetectionDelayTime", "driverBlocking",
        "dvAttributesPerEventType", "engines", "forensicsAutoTriggering",
        "identityConfigurationSettings", "identityEndpointReporting",
        "identityOn", "identityReportInterval",
        "identityThrottlingInterval", "identityUpdateInterval",
        "informationalAlertsOn", "inheritedFrom", "ioc", "iocAttributes",
        "iocSupported", "isDefault", "isDvPolicyPerEventType",
        "logCollectorEnabled", "mitigationMode",
        "mitigationModeSuspicious", "monitorOnExecute", "monitorOnWrite",
        "networkProtectionInfra", "networkQuarantineOn",
        "remoteOpsForensics", "remoteScriptOrchestration", "removeMacros",
        "removeMacrosMl", "researchOn", "scanNewAgents",
        "signedDriverBlockingOn", "snapshotsOn",
        "unsignedDriverBlockingOn", "updatedAt", "userFullName", "userId"
    }),
    ("PUT", "/accounts/{account_id}/reactivate"): frozenset({
        "data", "expiration", "unlimited"
    }),
    ("POST", "/accounts/{account_id}/uninstall-password/generate"): frozenset({
        "data", "expiration"
    }),
    ("POST", "/agents/actions/abort-scan"): frozenset({
        "data", "filter"
    }),
    ("POST", "/agents/actions/approve-stateless-upgrade"): frozenset({
        "data", "expiration", "filter"
    }),
    ("POST", "/agents/actions/approve-uninstall"): frozenset({
        "data", "filter"
    }),
    ("POST", "/agents/actions/broadcast"): frozenset({
        "data", "filter", "message"
    }),
    ("POST", "/agents/actions/can-start-remote-shell"): frozenset({
        "data", "filter"
    }),
    ("POST", "/agents/actions/clear-remote-shell-session"): frozenset({
        "data", "filter"
    }),
    ("POST", "/agents/actions/connect"): frozenset({
        "data", "filter"
    }),
    ("POST", "/agents/actions/decommission"): frozenset({
        "data", "filter"
    }),
    ("POST", "/agents/actions/disable-agent"): frozenset({
        "data", "expiration", "expirationTimezone", "filter",
        "shouldReboot"
    }),
    ("POST", "/agents/actions/disconnect"): frozenset({
        "data", "filter"
    }),
    ("POST", "/agents/actions/enable-agent"): frozenset({
        "data", "filter", "shouldReboot"
    }),
    ("POST", "/agents/actions/fetch-firewall-rules"): frozenset({
        "data", "filter", "format", "state"
    }),
    ("POST", "/agents/actions/fetch-installed-apps"): frozenset({
        "data", "filter"
    }),
    ("POST", "/agents/actions/fetch-logs"): frozenset({
        "agentLogs", "customerFacingLogs", "data", "filter",
        "platformLogs"
    }),
    ("POST", "/agents/actions/firewall-logging"): frozenset({
        "data", "filter", "reportLog", "reportMgmt"
    }),
    ("POST", "/agents/actions/initiate-scan"): frozenset({
        "data", "filter"
    }),
    ("POST", "/agents/actions/local-upgrade-authorization"): frozenset({
        "agentAuthorization", "data", "filter"
    }),
    ("POST", "/agents/actions/manage-tags"): frozenset({
        "data", "filter", "operation", "tagId"
    }),
    ("POST", "/agents/actions/mark-up-to-date"): frozenset({
        "data", "filter"
    }),
    ("POST", "/agents/actions/move-to-console"): frozenset({
        "data", "filter", "token"
    }),
    ("POST", "/agents/actions/move-to-site"): frozenset({
        "data", "filter", "targetSiteId"
    }),
    ("POST", "/agents/actions/randomize-uuid"): frozenset({
        "data", "filter"
    }),
    ("POST", "/agents/actions/ranger-disable"): frozenset({
        "data", "filter"
    }),
    ("POST", "/agents/actions/ranger-enable"): frozenset({
        "data", "filter"
    }),
    ("POST", "/agents/actions/reject-uninstall"): frozenset({
        "data", "filter"
    }),
    ("POST", "/agents/actions/reset-local-config"): frozenset({
        "data", "filter"
    }),
    ("POST", "/agents/actions/reset-passphrase"): frozenset({
        "data", "filter"
    }),
    ("POST", "/agents/actions/reset-passphrase/capability"): frozenset({
        "data", "filter"
    }),
    ("POST", "/agents/actions/restart-machine"): frozenset({
        "data", "filter"
    }),
    ("POST", "/agents/actions/set-config"): frozenset({
        "config", "data", "filter"
    }),
    ("POST", "/agents/actions/set-external-id"): frozenset({
        "data", "externalId", "filter"
    }),
    ("POST", "/agents/actions/shutdown"): frozenset({
        "data", "filter"
    }),
    ("POST", "/agents/actions/start-profiling"): frozenset({
        "data", "filter", "timeout"
    }),
    ("POST", "/agents/actions/start-remote-shell"): frozenset({
        "columns", "data", "filter", "historyPassword",
        "passwordFromScope", "rows", "twoFaCode"
    }),
    ("POST", "/agents/actions/stop-profiling"): frozenset({
        "data", "filter"
    }),
    ("POST", "/agents/actions/terminate-remote-shell"): frozenset({
        "channelId", "data", "filter"
    }),
    ("POST", "/agents/actions/uninstall"): frozenset({
        "data", "filter"
    }),
    ("POST", "/agents/actions/update-software"): frozenset({
        "allowDowngrade", "data", "fileName", "filter", "ignoreConflicts",
        "isScheduled", "osType", "packageId", "packageType", "path"
    }),
    ("POST", "/agents/disable-hyper-automation-pna"): frozenset({
        "data", "filter"
    }),
    ("POST", "/agents/enable-hyper-automation-pna"): frozenset({
        "data", "filter"
    }),
    ("POST", "/agents/{agent_id}/actions/fetch-files"): frozenset({
        "data", "files", "password"
    }),
    ("POST", "/application-management/scan"): frozenset({
        "filter"
    }),
    ("POST", "/application-management/settings"): frozenset({
        "data", "extensiveLinuxScanEnabled", "extensiveScanEnabled",
        "filter", "isDefaultPolicy", "scanSchedule",
        "vulnerabilitiesScanEnabled"
    }),
    ("POST", "/cloud-detection/alerts/analyst-verdict"): frozenset({
        "analystVerdict", "data", "filter"
    }),
    ("POST", "/cloud-detection/alerts/incident"): frozenset({
        "data", "filter", "incidentStatus"
    }),
    ("POST", "/cloud-detection/rules"): frozenset({
        "coolOffSettings", "correlationParams", "data", "description",
        "expiration", "expirationMode", "filter", "id", "name",
        "networkQuarantine", "queryLang", "queryType", "s1ql",
        "scheduledParams", "severity", "status", "templateRuleId",
        "treatAsThreat"
    }),
    ("PUT", "/cloud-detection/rules/disable"): frozenset({
        "filter"
    }),
    ("PUT", "/cloud-detection/rules/enable"): frozenset({
        "filter"
    }),
    ("PUT", "/cloud-detection/rules/{rule_id}"): frozenset({
        "coolOffSettings", "correlationParams", "data", "description",
        "expiration", "expirationMode", "filter", "id", "name",
        "networkQuarantine", "queryLang", "queryType", "s1ql",
        "scheduledParams", "severity", "status", "templateRuleId",
        "treatAsThreat"
    }),
    ("POST", "/cloud-funnel/estimator"): frozenset({
        "accountIds", "data", "desiredFields", "query", "siteIds"
    }),
    ("POST", "/cloud-funnel/onboarding"): frozenset({
        "accessKeyId", "accountId", "bucketUrl", "cloudProvider", "data",
        "desiredFields", "disableStream", "isInheriting", "query",
        "roleToAssume", "secretAccessKey", "siteIds", "useAssumeRole"
    }),
    ("POST", "/cloud-funnel/validate-bucket-permissions"): frozenset({
        "accessKeyId", "accountId", "bucketUrl", "cloudProvider", "data",
        "roleToAssume", "secretAccessKey", "siteId", "useAssumeRole"
    }),
    ("POST", "/cloud-funnel/validate-query"): frozenset({
        "data", "query"
    }),
    ("PUT", "/cnapp/vcs/integration/{integrationId}/repos/disable-scan"): frozenset({
        "data", "repositoryIds"
    }),
    ("PUT", "/cnapp/vcs/integration/{integrationId}/repos/edit-tags"): frozenset({
        "action", "data", "repositoryIds", "tagIds"
    }),
    ("PUT", "/cnapp/vcs/integration/{integrationId}/repos/enable-scan"): frozenset({
        "data", "repositoryIds"
    }),
    ("POST", "/cnapp/vcs/integration/{integrationId}/repos/get-tags"): frozenset({
        "data", "repositoryIds"
    }),
    ("PUT", "/cnapp/vcs/integrations/edit-tags"): frozenset({
        "action", "data", "integrationIds", "tagIds"
    }),
    ("POST", "/cnapp/vcs/onboarding"): frozenset({
        "azureOrganizationUrl", "azurePersonalAccessToken", "data",
        "description", "githubAppId", "githubAppPrivateKey",
        "githubInstallationId", "gitlabPersonalAccessToken", "provider",
        "serverHost", "serverPort", "settings", "tags", "title"
    }),
    ("POST", "/cnapp/vcs/scanner-policy"): frozenset({
        "branch", "data", "description", "name", "priority", "scope"
    }),
    ("PUT", "/cnapp/vcs/scanner-policy/{policyId}"): frozenset({
        "branch", "data", "description", "iacConfig", "name", "priority",
        "secretConfig", "tagIds", "vulnerabilityConfig"
    }),
    ("POST", "/cnapp/vcs/tunnel/user"): frozenset({
        "data", "gitlabPersonalAccessToken", "provider", "serverHost",
        "serverPort"
    }),
    ("POST", "/config-override"): frozenset({
        "account", "agentVersion", "config", "data", "description",
        "filter", "group", "name", "osType", "scope", "site",
        "versionOption"
    }),
    ("PUT", "/config-override/{override_id}"): frozenset({
        "account", "agentVersion", "config", "data", "description",
        "filter", "group", "name", "osType", "scope", "site",
        "versionOption"
    }),
    ("PUT", "/detection-library/platform-rules/settings"): frozenset({
        "disableInheritance", "scopeId", "scopeLevel"
    }),
    ("POST", "/device-control"): frozenset({
        "accessPermission", "action", "bluetoothAddress", "data",
        "deviceClass", "deviceId", "deviceInformationServiceInfoKey",
        "deviceInformationServiceInfoValue", "deviceName", "filter",
        "gattService", "interface", "manufacturerName", "minorClasses",
        "productId", "ruleName", "ruleType", "serviceClass", "status",
        "uid", "vendorId", "version"
    }),
    ("PUT", "/device-control/configuration"): frozenset({
        "data", "disableBleCommunication", "disableRfcomm",
        "disallowAccessPermissionControl", "enabled", "filter",
        "inheritedFrom", "inherits", "reportApproved", "reportBlocked",
        "reportReadOnly"
    }),
    ("POST", "/device-control/copy-rules"): frozenset({
        "accountId", "data", "filter", "groupIds", "siteId"
    }),
    ("PUT", "/device-control/enable"): frozenset({
        "data", "filter", "status"
    }),
    ("POST", "/device-control/move-rules"): frozenset({
        "accountId", "data", "filter", "groupIds", "siteId"
    }),
    ("PUT", "/device-control/reorder"): frozenset({
        "data", "filter", "id", "order"
    }),
    ("PUT", "/device-control/{rule_id}"): frozenset({
        "accessPermission", "action", "bluetoothAddress", "data",
        "deviceClass", "deviceId", "deviceInformationServiceInfoKey",
        "deviceInformationServiceInfoValue", "deviceName", "gattService",
        "interface", "manufacturerName", "minorClasses", "productId",
        "ruleName", "ruleType", "serviceClass", "status", "uid",
        "vendorId", "version"
    }),
    ("POST", "/dv/cancel-query"): frozenset({
        "queryId"
    }),
    ("POST", "/dv/events/pq"): frozenset({
        "accountIds", "fromDate", "limit", "query", "siteIds", "toDate"
    }),
    ("POST", "/dv/init-query"): frozenset({
        "accountIds", "fromDate", "isVerbose", "limit", "query",
        "queryType", "siteIds", "timeFrame", "toDate"
    }),
    ("POST", "/exclusions"): frozenset({
        "actions", "data", "description", "filter", "inject", "mode",
        "osType", "pathExclusionType", "source", "type", "value"
    }),
    ("PUT", "/exclusions"): frozenset({
        "actions", "data", "description", "id", "inject", "mode",
        "osType", "pathExclusionType", "sha256Value", "source", "type",
        "value"
    }),
    ("POST", "/exclusions/validate"): frozenset({
        "data", "exclusionType", "osType", "value"
    }),
    ("POST", "/export/agents-passphrases"): frozenset({
        "data", "filter"
    }),
    ("POST", "/filters"): frozenset({
        "data", "filter", "filterFields", "name", "scopeLevel", "siteId"
    }),
    ("POST", "/filters/dv"): frozenset({
        "data", "filter", "filterFields", "frequency", "name",
        "notifications", "recipients"
    }),
    ("PUT", "/filters/dv/{filter_id}"): frozenset({
        "data", "filter", "filterFields", "frequency", "name",
        "notifications", "recipients"
    }),
    ("PUT", "/filters/{filter_id}"): frozenset({
        "data", "filterFields", "name"
    }),
    ("POST", "/firewall-control"): frozenset({
        "action", "application", "data", "description", "direction",
        "filter", "localHost", "localPort", "location", "name", "osType",
        "osTypes", "protocol", "remoteHost", "remoteHosts", "remotePort",
        "status", "tag", "tagIds"
    }),
    ("POST", "/firewall-control/add-tags"): frozenset({
        "data", "filter", "tagIds"
    }),
    ("PUT", "/firewall-control/configuration"): frozenset({
        "data", "enabled", "filter", "inheritAllFirewallRules",
        "inheritSettings", "inheritedFrom", "inherits", "locationAware",
        "reportBlocked", "selectedTags"
    }),
    ("POST", "/firewall-control/copy-rules"): frozenset({
        "accountId", "accountIds", "data", "filter", "groupId",
        "groupIds", "siteId", "siteIds", "tenant"
    }),
    ("PUT", "/firewall-control/enable"): frozenset({
        "data", "filter", "status"
    }),
    ("POST", "/firewall-control/move-rules"): frozenset({
        "accountId", "accountIds", "data", "filter", "groupId",
        "groupIds", "siteId", "siteIds", "tenant"
    }),
    ("POST", "/firewall-control/remove-tags"): frozenset({
        "data", "filter", "tagIds"
    }),
    ("PUT", "/firewall-control/reorder"): frozenset({
        "data", "filter", "id", "order"
    }),
    ("POST", "/firewall-control/set-location"): frozenset({
        "data", "filter", "type", "values"
    }),
    ("POST", "/firewall-control/{firewall_rule_category}"): frozenset({
        "action", "application", "data", "description", "direction",
        "filter", "localHost", "localPort", "location", "name", "osType",
        "osTypes", "protocol", "remoteHost", "remoteHosts", "remotePort",
        "status", "tag", "tagIds"
    }),
    ("PUT", "/firewall-control/{firewall_rule_category}"): frozenset({
        "action", "application", "data", "description", "direction",
        "localHost", "localPort", "location", "name", "osType", "osTypes",
        "protocol", "remoteHost", "remoteHosts", "remotePort", "status",
        "tag", "tagIds"
    }),
    ("POST", "/firewall-control/{firewall_rule_category}/add-tags"): frozenset({
        "data", "filter", "tagIds"
    }),
    ("PUT", "/firewall-control/{firewall_rule_category}/configuration"): frozenset({
        "data", "enabled", "filter", "inheritAllFirewallRules",
        "inheritSettings", "inheritedFrom", "inherits", "locationAware",
        "reportBlocked", "selectedTags"
    }),
    ("POST", "/firewall-control/{firewall_rule_category}/copy-rules"): frozenset({
        "accountId", "accountIds", "data", "filter", "groupId",
        "groupIds", "siteId", "siteIds", "tenant"
    }),
    ("PUT", "/firewall-control/{firewall_rule_category}/enable"): frozenset({
        "data", "filter", "status"
    }),
    ("POST", "/firewall-control/{firewall_rule_category}/move-rules"): frozenset({
        "accountId", "accountIds", "data", "filter", "groupId",
        "groupIds", "siteId", "siteIds", "tenant"
    }),
    ("POST", "/firewall-control/{firewall_rule_category}/remove-tags"): frozenset({
        "data", "filter", "tagIds"
    }),
    ("PUT", "/firewall-control/{firewall_rule_category}/reorder"): frozenset({
        "data", "filter", "id", "order"
    }),
    ("POST", "/firewall-control/{firewall_rule_category}/set-location"): frozenset({
        "data", "filter", "type", "values"
    }),
    ("POST", "/groups"): frozenset({
        "data", "description", "filterId", "inherits", "isDefault",
        "name", "policy", "rank", "siteId", "source", "type"
    }),
    ("PUT", "/groups/ranks"): frozenset({
        "accountIds", "data", "filter", "ranks", "siteIds"
    }),
    ("PUT", "/groups/{group_id}/move-agents"): frozenset({
        "filter"
    }),
    ("PUT", "/groups/{group_id}/policy"): frozenset({
        "agentLoggingOn", "agentNotification", "agentUi", "agentUiOn",
        "allowRemoteShell", "allowUnprotectByApprovedProcess",
        "antiTamperingOn", "autoDecommissionDays", "autoDecommissionOn",
        "autoFileUpload", "autoImmuneOn", "autoMitigationAction",
        "cloudValidationOn", "createdAt", "data",
        "driftDetectionDelayTime", "driverBlocking",
        "dvAttributesPerEventType", "engines", "forensicsAutoTriggering",
        "identityConfigurationSettings", "identityEndpointReporting",
        "identityOn", "identityReportInterval",
        "identityThrottlingInterval", "identityUpdateInterval",
        "informationalAlertsOn", "inheritedFrom", "ioc", "iocAttributes",
        "iocSupported", "isDefault", "isDvPolicyPerEventType",
        "logCollectorEnabled", "mitigationMode",
        "mitigationModeSuspicious", "monitorOnExecute", "monitorOnWrite",
        "networkProtectionInfra", "networkQuarantineOn",
        "remoteOpsForensics", "remoteScriptOrchestration", "removeMacros",
        "removeMacrosMl", "researchOn", "scanNewAgents",
        "signedDriverBlockingOn", "snapshotsOn",
        "unsignedDriverBlockingOn", "updatedAt", "userFullName", "userId"
    }),
    ("POST", "/hyper-automate/api/public/workflow-import-export/import/batch"): frozenset({
        "body", "file", "filter"
    }),
    ("PUT", "/licenses/update-sites-modules"): frozenset({
        "data", "filter", "modules", "operation"
    }),
    ("POST", "/locations"): frozenset({
        "data", "description", "dnsLookup", "dnsServers", "filter",
        "ipAddresses", "name", "networkInterfaces", "operator",
        "registryKeys", "serverConnectivity"
    }),
    ("PUT", "/locations/{location_id}"): frozenset({
        "data", "description", "dnsLookup", "dnsServers", "ipAddresses",
        "name", "networkInterfaces", "operator", "registryKeys",
        "serverConnectivity"
    }),
    ("POST", "/log-collection/rules"): frozenset({
        "agentType", "description", "k8sParams", "linuxParams",
        "macosParams", "name", "scopeId", "scopeLevel", "windowsParams"
    }),
    ("POST", "/log-collection/rules/activation"): frozenset({
        "activate", "data", "filter"
    }),
    ("PUT", "/log-collection/rules/{rule_id}"): frozenset({
        "agentType", "description", "k8sParams", "linuxParams",
        "macosParams", "name", "scopeId", "scopeLevel", "windowsParams"
    }),
    ("POST", "/mobile-integration/mssp-provisioning/partner"): frozenset({
        "adminEmail", "adminFirstName", "adminLastName",
        "adminNotificationEmail", "data", "filter"
    }),
    ("POST", "/mobile-integration/provisioning/partner-key"): frozenset({
        "clientId", "data", "filter", "secret"
    }),
    ("PUT", "/mobile-integration/provisioning/partner-key"): frozenset({
        "clientId", "data", "filter", "secret"
    }),
    ("POST", "/mobile-integration/provisioning/tenant"): frozenset({
        "adminEmail", "adminFirstName", "adminLastName",
        "adminNotificationEmail", "data", "filter"
    }),
    ("POST", "/ranger-ad/get-affected-objects"): frozenset({
        "filter"
    }),
    ("POST", "/ranger-ad/set-ack-status"): frozenset({
        "filter"
    }),
    ("POST", "/ranger-ad/set-skipped-exposures"): frozenset({
        "filter"
    }),
    ("POST", "/ranger-ad/trigger-assessment"): frozenset({
        "filter"
    }),
    ("POST", "/ranger/cred-groups"): frozenset({
        "data", "domain", "groupName", "groupPassphrase", "scopeId",
        "targetOs"
    }),
    ("PUT", "/ranger/cred-groups/details/{detail_id}"): frozenset({
        "credType", "data", "encryptedCred", "encryptedKey", "title"
    }),
    ("POST", "/ranger/device-review"): frozenset({
        "data", "deviceReview", "filter", "reason", "reasonDetails"
    }),
    ("PUT", "/ranger/device-review/{inventory_id}"): frozenset({
        "data", "deviceReview", "reason", "reasonDetails"
    }),
    ("POST", "/ranger/enable-self-management"): frozenset({
        "data", "enable", "filter"
    }),
    ("POST", "/ranger/enablement"): frozenset({
        "data", "filter", "rangerEnabled", "rangerProEnabled",
        "roguesEnabled"
    }),
    ("POST", "/ranger/enablement/defaults"): frozenset({
        "data", "filter", "rangerEnabled", "rangerProEnabled",
        "roguesEnabled"
    }),
    ("POST", "/ranger/gateways/update"): frozenset({
        "allowScan", "archived", "data", "filter", "inheritSettings",
        "scanOnlyLocalSubnets"
    }),
    ("PUT", "/ranger/gateways/{gateway_id}"): frozenset({
        "accountId", "allowScan", "archived", "data", "icmpScan",
        "inheritSettings", "mdnsScan", "multiCastSsdpScan", "networkName",
        "rdnsScan", "restrictions", "scanOnlyLocalSubnets", "siteId",
        "smbScan", "snmpScan", "tcpPortScan", "tcpPorts", "udpPortScan",
        "udpPorts"
    }),
    ("PUT", "/ranger/settings"): frozenset({
        "accountId", "autoEnableNetworks", "combineDevices", "data",
        "enabled", "filter", "icmpScan", "mdnsScan",
        "minAgentsInNetworkToScan", "multiScanSsdp",
        "networkDecommissionValue", "newNetworkInHours", "rdnsScan",
        "restrictions", "scanOnlyLocalSubnets", "scopeId", "smbScan",
        "snapshotPeriod", "snmpScan", "specificPorts", "tcpPortScan",
        "tcpPorts", "udpPortScan", "udpPorts", "useFullDnsScan",
        "usePeriodicSnapshots", "useSpecificPorts"
    }),
    ("POST", "/ranger/tags"): frozenset({
        "data", "description", "filter", "id", "kind", "name"
    }),
    ("POST", "/rbac/role"): frozenset({
        "data", "description", "filter", "name", "permissionIds"
    }),
    ("PUT", "/rbac/role/{role_id}"): frozenset({
        "data", "description", "filter", "name", "permissionIds"
    }),
    ("POST", "/remote-ops/data-exporter/destination-profiles"): frozenset({
        "apiKey", "apiUrl", "destination", "isDefault", "name", "scopeId",
        "scopeLevel"
    }),
    ("POST", "/remote-ops/data-exporter/destination-profiles/set-default"): frozenset({
        "data", "profileId", "scopeId", "scopeLevel"
    }),
    ("PUT", "/remote-ops/data-exporter/destination-profiles/{profile_id}"): frozenset({
        "apiKey", "apiUrl", "data", "isDefault", "name"
    }),
    ("POST", "/remote-ops/forensics/collection-profiles"): frozenset({
        "artifacts", "data", "description", "name", "scopeId",
        "scopeLevel"
    }),
    ("PUT", "/remote-ops/forensics/collection-profiles/{profile_id}"): frozenset({
        "artifacts", "data", "description", "name"
    }),
    ("POST", "/remote-ops/forensics/start-collection"): frozenset({
        "collectionProfileId", "data", "description", "destination",
        "filter", "tag"
    }),
    ("POST", "/remote-ops/schedule/forensics"): frozenset({
        "action", "data", "filter", "scheduling"
    }),
    ("POST", "/remote-ops/schedule/remote-script"): frozenset({
        "action", "data", "filter", "scheduling"
    }),
    ("PUT", "/remote-ops/scheduled-tasks/{scheduled_task_id}"): frozenset({
        "data", "scheduling"
    }),
    ("POST", "/remote-scripts/execute"): frozenset({
        "apiKey", "data", "destinationProfileId",
        "destinationProfileKeyword", "filter", "inputParams",
        "outputDestination", "outputDirectory", "outputFilePaths",
        "password", "passwordFromScope", "requiresApproval", "scriptId",
        "scriptRuntimeTimeoutSeconds", "singularityxdrKeyword",
        "singularityxdrUrl", "taskDescription"
    }),
    ("POST", "/remote-scripts/fetch-files"): frozenset({
        "computerNames", "data", "taskIds"
    }),
    ("POST", "/remote-scripts/guardrails/check"): frozenset({
        "agentIds", "data", "scriptId"
    }),
    ("POST", "/remote-scripts/guardrails/configuration"): frozenset({
        "data", "enabled", "endpointsQuantity", "scopeId", "scopeLevel",
        "scriptTypes"
    }),
    ("PUT", "/remote-scripts/pending-executions/{pending_execution_id}"): frozenset({
        "action", "data"
    }),
    ("PUT", "/remote-scripts/{script_id}"): frozenset({
        "consoleData", "data", "inputExample", "inputInstructions",
        "inputRequired", "osTypes", "packageEndpointExpiration",
        "packageEndpointExpirationSeconds", "scriptDescription",
        "scriptName", "scriptRuntimeTimeoutSeconds", "scriptType",
        "sendActivity"
    }),
    ("POST", "/report-tasks"): frozenset({
        "attachmentTypes", "data", "day", "filter", "frequency",
        "fromDate", "insightTypes", "isTrend", "name", "recipients",
        "scheduleType", "toDate"
    }),
    ("POST", "/restrictions"): frozenset({
        "data", "description", "filter", "osType", "sha256Value",
        "source", "type", "value"
    }),
    ("PUT", "/restrictions"): frozenset({
        "data", "description", "filter", "id", "osType", "sha256Value",
        "source", "type", "value"
    }),
    ("POST", "/restrictions/validate"): frozenset({
        "data", "filter", "osType", "sha256Value", "value"
    }),
    ("PUT", "/rogues/settings"): frozenset({
        "accountId", "data", "enabled", "filter",
        "minAgentsInNetworkToScan", "restrictions", "specificPorts",
        "useSpecificPorts"
    }),
    ("POST", "/service-users"): frozenset({
        "data", "description", "expirationDate", "forceLegacy", "name",
        "scope", "scopeRoles"
    }),
    ("POST", "/service-users/delete-service-users"): frozenset({
        "data", "filter"
    }),
    ("PUT", "/service-users/{service_user_id}"): frozenset({
        "data", "description", "scope", "scopeRoles"
    }),
    ("PUT", "/settings/active-directory"): frozenset({
        "data", "enabled", "host", "password", "port", "rootDn", "ssl",
        "username"
    }),
    ("PUT", "/settings/active-directory/scope-mapping"): frozenset({
        "admin", "data", "filter", "viewer"
    }),
    ("POST", "/settings/active-directory/test"): frozenset({
        "data", "enabled", "host", "password", "port", "rootDn", "ssl",
        "username"
    }),
    ("PUT", "/settings/microsoft"): frozenset({
        "data", "enabled", "expiryDate", "filter", "inherits", "url"
    }),
    ("POST", "/settings/microsoft/test"): frozenset({
        "data", "enabled", "expiryDate", "filter", "inherits", "url"
    }),
    ("PUT", "/settings/notifications"): frozenset({
        "configurations", "data", "filter", "lastModified",
        "notifications"
    }),
    ("POST", "/settings/notifications/cancel-pending-emails"): frozenset({
        "filter"
    }),
    ("PUT", "/settings/recipients"): frozenset({
        "createdAt", "data", "email", "filter", "id", "name", "sms",
        "updatedAt"
    }),
    ("PUT", "/settings/sms"): frozenset({
        "data", "enabled", "filter"
    }),
    ("PUT", "/settings/smtp"): frozenset({
        "data", "enabled", "encryption", "filter", "host", "inherits",
        "noReplyEmail", "password", "port", "username"
    }),
    ("POST", "/settings/smtp/test"): frozenset({
        "data", "enabled", "encryption", "filter", "host", "inherits",
        "noReplyEmail", "password", "port", "username"
    }),
    ("PUT", "/settings/sso"): frozenset({
        "autoProvisioning", "data", "defaultUserRole",
        "defaultUserRoleId", "domains", "enabled", "filter",
        "idpCertContent", "idpCertName", "idpEntityId", "idpSsoUrl",
        "signRequest", "ssoElevatedSessionReauthType",
        "ssoInheritDomainsFrom", "ssoPropagateDomainsToChildren"
    }),
    ("POST", "/settings/sso/test"): frozenset({
        "autoProvisioning", "data", "defaultUserRole",
        "defaultUserRoleId", "domains", "enabled", "filter",
        "idpCertContent", "idpCertName", "idpEntityId", "idpSsoUrl",
        "signRequest", "ssoElevatedSessionReauthType",
        "ssoInheritDomainsFrom", "ssoPropagateDomainsToChildren"
    }),
    ("PUT", "/settings/syslog"): frozenset({
        "clientCertContent", "clientCertName", "clientKeyContent",
        "clientKeyName", "data", "enabled", "filter", "format", "host",
        "port", "serverCertContent", "serverCertName", "ssl", "token"
    }),
    ("POST", "/settings/syslog/test"): frozenset({
        "clientCertContent", "clientCertName", "clientKeyContent",
        "clientKeyName", "data", "enabled", "filter", "format", "host",
        "port", "serverCertContent", "serverCertName", "ssl", "token"
    }),
    ("POST", "/singularity-marketplace/applications"): frozenset({
        "applicationInstanceName", "configurations", "data", "filter"
    }),
    ("PUT", "/singularity-marketplace/applications"): frozenset({
        "applicationIdToNameMap", "configurations", "data", "filter"
    }),
    ("POST", "/singularity-marketplace/applications/{applicationMode}"): frozenset({
        "filter"
    }),
    ("POST", "/site-with-admin"): frozenset({
        "accountId", "accountSfId", "data", "description", "expiration",
        "externalId", "inheritAccountExpiration", "inherits", "irFields",
        "licenses", "name", "policy", "siteType", "sku", "suite",
        "totalLicenses", "unlimitedExpiration", "unlimitedLicenses",
        "usageType", "user"
    }),
    ("POST", "/sites"): frozenset({
        "accountId", "accountSfId", "data", "description", "expiration",
        "externalId", "inheritAccountExpiration", "inherits", "irFields",
        "licenses", "name", "policy", "siteType", "sku", "suite",
        "totalLicenses", "unlimitedExpiration", "unlimitedLicenses",
        "usageType"
    }),
    ("POST", "/sites/duplicate-site"): frozenset({
        "copyUsers", "data", "name", "policy", "policySource",
        "sourceSiteId", "totalLicenses", "unlimitedLicenses"
    }),
    ("PUT", "/sites/update-bulk"): frozenset({
        "data", "description", "expiration", "filter",
        "inheritAccountExpiration", "inherits", "licenses", "siteType",
        "unlimitedExpiration"
    }),
    ("PUT", "/sites/{site_id}"): frozenset({
        "data", "description", "expiration", "externalId", "id",
        "inheritAccountExpiration", "inherits", "irFields", "licenses",
        "name", "policy", "siteType", "suite", "totalLicenses",
        "unlimitedExpiration", "unlimitedLicenses", "usageType"
    }),
    ("PUT", "/sites/{site_id}/policy"): frozenset({
        "agentLoggingOn", "agentNotification", "agentUi", "agentUiOn",
        "allowRemoteShell", "allowUnprotectByApprovedProcess",
        "antiTamperingOn", "autoDecommissionDays", "autoDecommissionOn",
        "autoFileUpload", "autoImmuneOn", "autoMitigationAction",
        "cloudValidationOn", "createdAt", "data",
        "driftDetectionDelayTime", "driverBlocking",
        "dvAttributesPerEventType", "engines", "forensicsAutoTriggering",
        "identityConfigurationSettings", "identityEndpointReporting",
        "identityOn", "identityReportInterval",
        "identityThrottlingInterval", "identityUpdateInterval",
        "informationalAlertsOn", "inheritedFrom", "ioc", "iocAttributes",
        "iocSupported", "isDefault", "isDvPolicyPerEventType",
        "logCollectorEnabled", "mitigationMode",
        "mitigationModeSuspicious", "monitorOnExecute", "monitorOnWrite",
        "networkProtectionInfra", "networkQuarantineOn",
        "remoteOpsForensics", "remoteScriptOrchestration", "removeMacros",
        "removeMacrosMl", "researchOn", "scanNewAgents",
        "signedDriverBlockingOn", "snapshotsOn",
        "unsignedDriverBlockingOn", "updatedAt", "userFullName", "userId"
    }),
    ("PUT", "/sites/{site_id}/reactivate"): frozenset({
        "data", "expiration", "unlimited"
    }),
    ("PUT", "/system/configuration"): frozenset({
        "accessibleUrl", "advancedMode", "allowDuplicateSite",
        "allowedDomains", "cloudIntelligenceOn",
        "cloudLastConnectionTime", "data", "earlyAccess",
        "earlyAccessPlatforms", "filter", "globalTwoFaEnabled",
        "passwordExpiration", "rememberMeLength",
        "tfaEnrollmentExpiration", "uiInactivityTimeoutSeconds"
    }),
    ("POST", "/tag-manager"): frozenset({
        "data", "description", "filter", "key", "type", "value"
    }),
    ("PUT", "/tag-manager/{tag_id}"): frozenset({
        "data", "description", "key", "value"
    }),
    ("POST", "/tags"): frozenset({
        "data", "description", "filter", "id", "kind", "name", "type"
    }),
    ("PUT", "/tags/{tag_id}"): frozenset({
        "data", "description", "id", "kind", "name"
    }),
    ("PUT", "/tasks-configuration"): frozenset({
        "data", "filter", "inheritParentConcurrencyConfig",
        "inheritParentMaintenanceConfig", "maintenanceWindowsByDay",
        "maxConcurrent", "timezoneGmt"
    }),
    ("PUT", "/tasks-configuration/flexible"): frozenset({
        "active", "data", "end", "filter", "frequency",
        "inheritParentConcurrencyConfig",
        "inheritParentMaintenanceConfig", "interval", "maxConcurrent",
        "rules", "startsOn", "timezone"
    }),
    ("PUT", "/tenant/policy"): frozenset({
        "agentLoggingOn", "agentNotification", "agentUi", "agentUiOn",
        "allowRemoteShell", "allowUnprotectByApprovedProcess",
        "antiTamperingOn", "autoDecommissionDays", "autoDecommissionOn",
        "autoFileUpload", "autoImmuneOn", "autoMitigationAction",
        "cloudValidationOn", "createdAt", "data",
        "driftDetectionDelayTime", "driverBlocking",
        "dvAttributesPerEventType", "engines", "forensicsAutoTriggering",
        "identityConfigurationSettings", "identityEndpointReporting",
        "identityOn", "identityReportInterval",
        "identityThrottlingInterval", "identityUpdateInterval",
        "informationalAlertsOn", "inheritedFrom", "ioc", "iocAttributes",
        "iocSupported", "isDefault", "isDvPolicyPerEventType",
        "logCollectorEnabled", "mitigationMode",
        "mitigationModeSuspicious", "monitorOnExecute", "monitorOnWrite",
        "networkProtectionInfra", "networkQuarantineOn",
        "remoteOpsForensics", "remoteScriptOrchestration", "removeMacros",
        "removeMacrosMl", "researchOn", "scanNewAgents",
        "signedDriverBlockingOn", "snapshotsOn",
        "unsignedDriverBlockingOn", "updatedAt", "userFullName", "userId"
    }),
    ("POST", "/threat-intelligence/iocs"): frozenset({
        "campaignNames", "category", "creationTime", "creator", "data",
        "description", "externalId", "filter", "intrusionSets", "labels",
        "malwareNames", "metadata", "method", "mitreTactic", "name",
        "originalRiskScore", "pattern", "patternType", "reference",
        "severity", "source", "threatActorTypes", "threatActors", "type",
        "validUntil", "value"
    }),
    ("POST", "/threat-intelligence/iocs/stix"): frozenset({
        "bundle", "filter"
    }),
    ("POST", "/threat-intelligence/user-config"): frozenset({
        "data", "description", "disableRh", "disableThreat",
        "enableXdrMatching", "excludeTii", "filter",
        "threatExcludeFields", "threatMinScore"
    }),
    ("POST", "/threats/actions/container-network-connect"): frozenset({
        "containerId", "data", "filter"
    }),
    ("POST", "/threats/actions/container-network-disconnect"): frozenset({
        "containerId", "data", "filter"
    }),
    ("POST", "/threats/add-to-blacklist"): frozenset({
        "data", "description", "externalTicketId", "filter", "note",
        "targetScope"
    }),
    ("POST", "/threats/add-to-exclusions"): frozenset({
        "actions", "data", "description", "externalTicketId", "filter",
        "macroModules", "mode", "note", "pathExclusionType",
        "targetScope", "type", "value"
    }),
    ("POST", "/threats/analyst-verdict"): frozenset({
        "analystVerdict", "data", "filter"
    }),
    ("POST", "/threats/dv-add-to-blacklist"): frozenset({
        "data", "hashes", "targetScope"
    }),
    ("POST", "/threats/dv-mark-as-threat"): frozenset({
        "data", "events", "initiatedBy", "status"
    }),
    ("POST", "/threats/external-ticket-id"): frozenset({
        "data", "externalTicketId", "filter"
    }),
    ("POST", "/threats/fetch-file"): frozenset({
        "data", "filter", "password"
    }),
    ("POST", "/threats/incident"): frozenset({
        "analystVerdict", "data", "filter", "incidentStatus"
    }),
    ("POST", "/threats/mitigate-alerts"): frozenset({
        "action", "alerts", "data"
    }),
    ("POST", "/threats/mitigate/{action}"): frozenset({
        "data", "filter"
    }),
    ("POST", "/threats/notes"): frozenset({
        "data", "filter", "text"
    }),
    ("PUT", "/threats/{threat_id}/notes/{note_id}"): frozenset({
        "data", "text"
    }),
    ("POST", "/unified-exclusions/bulk"): frozenset({
        "data", "filter"
    }),
    ("PUT", "/update/agent/packages/{package_id}"): frozenset({
        "accountIds", "data", "minorVersion", "osArch", "rangerVersion",
        "scopeLevel", "siteIds", "status", "supportedOsVersions",
        "version"
    }),
    ("POST", "/users"): frozenset({
        "allowRemoteShell", "data", "email", "forceCredentialAuth",
        "fullName", "password", "scope", "scopeRoles", "siteRoles",
        "tenantRoles", "twoFaEnabled"
    }),
    ("POST", "/users/2fa/disable"): frozenset({
        "currentPassword", "data", "id", "twoFaCode"
    }),
    ("POST", "/users/2fa/enable"): frozenset({
        "currentPassword", "data", "id", "twoFaCode"
    }),
    ("POST", "/users/auth/app"): frozenset({
        "code", "data", "rememberMe"
    }),
    ("POST", "/users/auth/elevate"): frozenset({
        "code", "data"
    }),
    ("POST", "/users/change-password"): frozenset({
        "confirmNewPassword", "currentPassword", "data", "id",
        "newPassword", "twoFaCode"
    }),
    ("POST", "/users/delete-2fa"): frozenset({
        "data", "ids"
    }),
    ("POST", "/users/delete-users"): frozenset({
        "data", "filter"
    }),
    ("POST", "/users/enable-app"): frozenset({
        "code", "data", "id"
    }),
    ("POST", "/users/enroll-2fa"): frozenset({
        "data", "ids"
    }),
    ("POST", "/users/generate-iframe-token"): frozenset({
        "accountId", "agentUuids", "data", "role", "roleName", "userName"
    }),
    ("POST", "/users/login"): frozenset({
        "password", "rememberMe", "username"
    }),
    ("POST", "/users/login-continue"): frozenset({
        "data", "dontShowAgain", "resetPassword", "token"
    }),
    ("POST", "/users/login/force-reset-password-on-login"): frozenset({
        "data", "filter"
    }),
    ("POST", "/users/login/send-reset-password-email"): frozenset({
        "data", "filter"
    }),
    ("POST", "/users/login/set-password"): frozenset({
        "data", "password", "token"
    }),
    ("POST", "/users/onboarding/send-verification-email"): frozenset({
        "data", "filter"
    }),
    ("POST", "/users/onboarding/verify"): frozenset({
        "data", "password", "resetPasswordFlow", "token"
    }),
    ("POST", "/users/reset-2fa"): frozenset({
        "data", "enroll", "ids"
    }),
    ("POST", "/users/revoke-api-token"): frozenset({
        "currentPassword", "data", "id", "twoFaCode"
    }),
    ("PUT", "/users/{user_id}"): frozenset({
        "allowRemoteShell", "canGenerateApiToken", "currentPassword",
        "data", "email", "fullName", "id", "password", "scope",
        "scopeRoles", "siteRoles", "tenantRoles", "twoFaCode",
        "twoFaEnabled"
    }),
    ("POST", "/xdr/action-controller/perform-unified-action"): frozenset({
        "actionPath", "id__in", "id__nin", "payload"
    }),
    ("POST", "/xdr/action-controller/perform-unified-action/notify"): frozenset({
        "actionPath", "id__in", "id__nin", "notifyOnly", "payload"
    }),
    ("POST", "/xdr/assets"): frozenset({
        "data", "filter"
    }),
    ("POST", "/xdr/assets/account"): frozenset({
        "data", "filter"
    }),
    ("POST", "/xdr/assets/account/action"): frozenset({
        "actionName", "id__in", "id__nin"
    }),
    ("POST", "/xdr/assets/action"): frozenset({
        "actionName", "id__in", "id__nin"
    }),
    ("POST", "/xdr/assets/actions/perform-unified-action"): frozenset({
        "actionPath", "id__in", "id__nin", "payload"
    }),
    ("POST", "/xdr/assets/ai-ml"): frozenset({
        "data", "filter"
    }),
    ("POST", "/xdr/assets/ai-ml/action"): frozenset({
        "actionName", "id__in", "id__nin"
    }),
    ("POST", "/xdr/assets/application-integration"): frozenset({
        "data", "filter"
    }),
    ("POST", "/xdr/assets/application-integration/action"): frozenset({
        "actionName", "id__in", "id__nin"
    }),
    ("POST", "/xdr/assets/cloud-application"): frozenset({
        "data", "filter"
    }),
    ("POST", "/xdr/assets/cloud-application/action"): frozenset({
        "actionName", "id__in", "id__nin"
    }),
    ("POST", "/xdr/assets/container"): frozenset({
        "data", "filter"
    }),
    ("POST", "/xdr/assets/container/action"): frozenset({
        "actionName", "id__in", "id__nin"
    }),
    ("POST", "/xdr/assets/data-analysis"): frozenset({
        "data", "filter"
    }),
    ("POST", "/xdr/assets/data-analysis/action"): frozenset({
        "actionName", "id__in", "id__nin"
    }),
    ("POST", "/xdr/assets/data-store"): frozenset({
        "data", "filter"
    }),
    ("POST", "/xdr/assets/data-store/action"): frozenset({
        "actionName", "id__in", "id__nin"
    }),
    ("POST", "/xdr/assets/developer-tool"): frozenset({
        "data", "filter"
    }),
    ("POST", "/xdr/assets/developer-tool/action"): frozenset({
        "actionName", "id__in", "id__nin"
    }),
    ("POST", "/xdr/assets/device"): frozenset({
        "data", "filter"
    }),
    ("POST", "/xdr/assets/device/action"): frozenset({
        "actionName", "id__in", "id__nin"
    }),
    ("POST", "/xdr/assets/function"): frozenset({
        "data", "filter"
    }),
    ("POST", "/xdr/assets/function/action"): frozenset({
        "actionName", "id__in", "id__nin"
    }),
    ("POST", "/xdr/assets/governance"): frozenset({
        "data", "filter"
    }),
    ("POST", "/xdr/assets/governance/action"): frozenset({
        "actionName", "id__in", "id__nin"
    }),
    ("POST", "/xdr/assets/identity"): frozenset({
        "data", "filter"
    }),
    ("POST", "/xdr/assets/identity/action"): frozenset({
        "actionName", "id__in", "id__nin"
    }),
    ("POST", "/xdr/assets/network"): frozenset({
        "data", "filter"
    }),
    ("POST", "/xdr/assets/network/action"): frozenset({
        "actionName", "id__in", "id__nin"
    }),
    ("POST", "/xdr/assets/server"): frozenset({
        "data", "filter"
    }),
    ("POST", "/xdr/assets/server/action"): frozenset({
        "actionName", "id__in", "id__nin"
    }),
    ("POST", "/xdr/assets/storage"): frozenset({
        "data", "filter"
    }),
    ("POST", "/xdr/assets/storage/action"): frozenset({
        "actionName", "id__in", "id__nin"
    }),
    ("POST", "/xdr/assets/surface/cloud/action"): frozenset({
        "actionName", "id__in", "id__nin"
    }),
    ("POST", "/xdr/assets/surface/endpoint"): frozenset({
        "data", "filter"
    }),
    ("POST", "/xdr/assets/surface/endpoint/action"): frozenset({
        "actionName", "id__in", "id__nin"
    }),
    ("POST", "/xdr/assets/surface/identity/action"): frozenset({
        "actionName", "id__in", "id__nin"
    }),
    ("POST", "/xdr/assets/surface/networkDiscovery/action"): frozenset({
        "actionName", "id__in", "id__nin"
    }),
    ("POST", "/xdr/assets/tags/rules"): frozenset({
        "accountId", "conditions", "createdAt", "createdByEmail",
        "createdById", "description", "excludedAssets", "id", "mgmtId",
        "name", "scopes", "siteId", "status", "tags", "updatedAt",
        "updatedByEmail", "updatedById"
    }),
    ("PUT", "/xdr/assets/tags/rules"): frozenset({
        "accountId", "conditions", "createdAt", "createdByEmail",
        "createdById", "description", "excludedAssets", "id", "mgmtId",
        "name", "scopes", "siteId", "status", "tags", "updatedAt",
        "updatedByEmail", "updatedById"
    }),
    ("POST", "/xdr/assets/tags/rules/test"): frozenset({
        "accountId", "conditions", "createdAt", "createdByEmail",
        "createdById", "description", "excludedAssets", "id", "mgmtId",
        "name", "scopes", "siteId", "status", "tags", "updatedAt",
        "updatedByEmail", "updatedById"
    }),
    ("POST", "/xdr/assets/workstation"): frozenset({
        "data", "filter"
    }),
    ("POST", "/xdr/assets/workstation/action"): frozenset({
        "actionName", "id__in", "id__nin"
    }),
    ("POST", "/xdr/filters"): frozenset({
        "data", "filter", "filterFields", "name", "scopeId", "scopeLevel",
        "visibility"
    }),
    ("PUT", "/xdr/filters/{filter_id}"): frozenset({
        "data", "filter", "filterFields", "name"
    }),
    ("POST", "/xdr/graph-explorer/query/explorer"): frozenset({
        "search"
    }),
    ("POST", "/xdr/graph-explorer/query/explorer/v2"): frozenset({
        "name", "search"
    }),
    ("POST", "/xdr/graph-explorer/query/management/query"): frozenset({
        "name", "query", "queryDescription", "shared"
    }),
    ("PUT", "/xdr/graph-explorer/query/management/query/{query_id}"): frozenset({
        "name", "query", "queryDescription", "shared"
    }),
}
