"""Integration tests for Elastic Security Detection Engine Signals (Alerts) API.

Verifies signal search, status updates, tag management, and assignee
management at ``/kibana/api/detection_engine/signals``.
"""
import base64

from fastapi.testclient import TestClient

ES_AUTH = {
    "Authorization": "Basic " + base64.b64encode(b"elastic:mock-elastic-password").decode(),
}

KBN_WRITE_HEADERS = {
    **ES_AUTH,
    "kbn-xsrf": "true",
}


def _get_alert_ids(client: TestClient, count: int = 2) -> list[str]:
    """Return a list of seeded alert IDs by searching signals.

    The repo key is the ``id`` field inside ``_source``, not the
    Elasticsearch ``_id`` (which is a random UUID generated by
    ``wrap_as_hits``).
    """
    resp = client.post(
        "/kibana/api/detection_engine/signals/search",
        headers=ES_AUTH,
        json={"query": {"match_all": {}}, "size": count},
    )
    return [h["_source"]["id"] for h in resp.json()["hits"]["hits"]]


class TestSignalsSearch:
    """Tests for POST /kibana/api/detection_engine/signals/search."""

    def test_search_returns_200(self, client: TestClient) -> None:
        """Signals search should return 200 with valid auth."""
        resp = client.post(
            "/kibana/api/detection_engine/signals/search",
            headers=ES_AUTH,
            json={"query": {"match_all": {}}},
        )
        assert resp.status_code == 200

    def test_search_response_has_es_envelope(self, client: TestClient) -> None:
        """Response must use the Elasticsearch hits envelope format."""
        body = client.post(
            "/kibana/api/detection_engine/signals/search",
            headers=ES_AUTH,
            json={"query": {"match_all": {}}},
        ).json()
        assert "hits" in body
        assert "total" in body["hits"]
        assert body["hits"]["total"]["relation"] == "eq"
        assert "hits" in body["hits"]

    def test_search_returns_45_seeded_alerts(self, client: TestClient) -> None:
        """Seeder creates 45 alerts; total should reflect that."""
        body = client.post(
            "/kibana/api/detection_engine/signals/search",
            headers=ES_AUTH,
            json={"query": {"match_all": {}}, "size": 100},
        ).json()
        assert body["hits"]["total"]["value"] == 45

    def test_search_with_size_limits_hits(self, client: TestClient) -> None:
        """Size parameter should limit the number of returned hits."""
        body = client.post(
            "/kibana/api/detection_engine/signals/search",
            headers=ES_AUTH,
            json={"size": 3},
        ).json()
        assert len(body["hits"]["hits"]) <= 3

    def test_search_hit_has_source_fields(self, client: TestClient) -> None:
        """Each hit should have _source with alert-relevant fields."""
        body = client.post(
            "/kibana/api/detection_engine/signals/search",
            headers=ES_AUTH,
            json={"size": 1},
        ).json()
        source = body["hits"]["hits"][0]["_source"]
        expected = [
            "id", "signal_status", "signal_rule_name",
            "agent_id", "hostname", "process_name",
            "timestamp", "workflow_status",
        ]
        for field in expected:
            assert field in source, f"Missing alert field: {field}"


class TestUpdateSignalStatus:
    """Tests for POST /kibana/api/detection_engine/signals/status."""

    def test_close_alert(self, client: TestClient) -> None:
        """Setting status to 'closed' should update the alert."""
        alert_ids = _get_alert_ids(client, 1)
        resp = client.post(
            "/kibana/api/detection_engine/signals/status",
            headers=KBN_WRITE_HEADERS,
            json={"signal_ids": alert_ids, "status": "closed"},
        )
        assert resp.status_code == 200
        assert resp.json()["updated"] == 1

    def test_acknowledge_alert(self, client: TestClient) -> None:
        """Setting status to 'acknowledged' should succeed."""
        alert_ids = _get_alert_ids(client, 1)
        resp = client.post(
            "/kibana/api/detection_engine/signals/status",
            headers=KBN_WRITE_HEADERS,
            json={"signal_ids": alert_ids, "status": "acknowledged"},
        )
        assert resp.status_code == 200
        assert resp.json()["updated"] == 1

    def test_status_update_persists(self, client: TestClient) -> None:
        """After closing an alert, searching by status should reflect it."""
        alert_ids = _get_alert_ids(client, 1)
        client.post(
            "/kibana/api/detection_engine/signals/status",
            headers=KBN_WRITE_HEADERS,
            json={"signal_ids": alert_ids, "status": "closed"},
        )
        # Verify via Elasticsearch search that the alert is now closed
        body = client.post(
            "/elastic/.siem-signals-default/_search",
            headers=ES_AUTH,
            json={"query": {"term": {"id": alert_ids[0]}}, "size": 1},
        ).json()
        hits = body["hits"]["hits"]
        assert len(hits) == 1
        assert hits[0]["_source"]["workflow_status"] == "closed"

    def test_missing_signal_ids_returns_400(self, client: TestClient) -> None:
        """Missing signal_ids should return 400."""
        resp = client.post(
            "/kibana/api/detection_engine/signals/status",
            headers=KBN_WRITE_HEADERS,
            json={"status": "closed"},
        )
        assert resp.status_code == 400

    def test_missing_status_returns_400(self, client: TestClient) -> None:
        """Missing status field should return 400."""
        resp = client.post(
            "/kibana/api/detection_engine/signals/status",
            headers=KBN_WRITE_HEADERS,
            json={"signal_ids": ["some-id"]},
        )
        assert resp.status_code == 400

    def test_missing_kbn_xsrf_returns_400(self, client: TestClient) -> None:
        """Missing kbn-xsrf header should return 400."""
        alert_ids = _get_alert_ids(client, 1)
        resp = client.post(
            "/kibana/api/detection_engine/signals/status",
            headers=ES_AUTH,
            json={"signal_ids": alert_ids, "status": "closed"},
        )
        assert resp.status_code == 400


class TestUpdateSignalTags:
    """Tests for POST /kibana/api/detection_engine/signals/tags."""

    def test_add_tags(self, client: TestClient) -> None:
        """Adding tags should succeed and return updated count."""
        alert_ids = _get_alert_ids(client, 1)
        resp = client.post(
            "/kibana/api/detection_engine/signals/tags",
            headers=KBN_WRITE_HEADERS,
            json={
                "ids": alert_ids,
                "tags": {"tags_to_add": ["investigation", "priority-high"], "tags_to_remove": []},
            },
        )
        assert resp.status_code == 200
        assert resp.json()["updated"] == 1

    def test_remove_tags(self, client: TestClient) -> None:
        """Removing tags should succeed."""
        alert_ids = _get_alert_ids(client, 1)
        # All seeded alerts have ["Elastic", "Endpoint"] tags
        resp = client.post(
            "/kibana/api/detection_engine/signals/tags",
            headers=KBN_WRITE_HEADERS,
            json={
                "ids": alert_ids,
                "tags": {"tags_to_add": [], "tags_to_remove": ["Endpoint"]},
            },
        )
        assert resp.status_code == 200
        assert resp.json()["updated"] == 1

    def test_missing_ids_returns_400(self, client: TestClient) -> None:
        """Missing ids should return 400."""
        resp = client.post(
            "/kibana/api/detection_engine/signals/tags",
            headers=KBN_WRITE_HEADERS,
            json={"tags": {"tags_to_add": ["test"]}},
        )
        assert resp.status_code == 400


class TestUpdateSignalAssignees:
    """Tests for POST /kibana/api/detection_engine/signals/assignees."""

    def test_add_assignees(self, client: TestClient) -> None:
        """Adding assignees should succeed and return updated count."""
        alert_ids = _get_alert_ids(client, 1)
        resp = client.post(
            "/kibana/api/detection_engine/signals/assignees",
            headers=KBN_WRITE_HEADERS,
            json={
                "ids": alert_ids,
                "assignees": {
                    "assignees_to_add": [{"uid": "analyst-001"}],
                    "assignees_to_remove": [],
                },
            },
        )
        assert resp.status_code == 200
        assert resp.json()["updated"] == 1

    def test_remove_assignees(self, client: TestClient) -> None:
        """Removing assignees should succeed."""
        alert_ids = _get_alert_ids(client, 1)
        # First add, then remove
        client.post(
            "/kibana/api/detection_engine/signals/assignees",
            headers=KBN_WRITE_HEADERS,
            json={
                "ids": alert_ids,
                "assignees": {
                    "assignees_to_add": [{"uid": "to-remove"}],
                    "assignees_to_remove": [],
                },
            },
        )
        resp = client.post(
            "/kibana/api/detection_engine/signals/assignees",
            headers=KBN_WRITE_HEADERS,
            json={
                "ids": alert_ids,
                "assignees": {
                    "assignees_to_add": [],
                    "assignees_to_remove": [{"uid": "to-remove"}],
                },
            },
        )
        assert resp.status_code == 200
        assert resp.json()["updated"] == 1

    def test_missing_ids_returns_400(self, client: TestClient) -> None:
        """Missing ids should return 400."""
        resp = client.post(
            "/kibana/api/detection_engine/signals/assignees",
            headers=KBN_WRITE_HEADERS,
            json={"assignees": {"assignees_to_add": [{"uid": "user"}]}},
        )
        assert resp.status_code == 400
