"""Derive what the SentinelOne swagger says each write body must carry.

`body_audit.py` found twenty-five write routes that answered 200 to an empty
body. The swagger says what those bodies are made of: every one of them
declares `data`, `filter` or both as *required*, and declares the members
each of those objects holds. A route that takes a body carrying none of them
is taking a body the vendor's own reference says is not one.

This reads the 2.1 swagger and writes, per route:

    backend/application/documented_bodies.py

the top-level members the schema marks required, together with the members
of the `data` payload — the mock also accepts the flat form of these bodies,
so a client sending `data`'s members without the wrapper has still sent
something the route knows. `filter`'s own members are left out: they are the
whole agent-filter vocabulary, hundreds of names that say nothing about
whether a body is a body.

Nothing is guessed. A route the swagger documents no body for is left out,
and so is one whose body declares nothing required — the guard exists to
refuse a body that carries *nothing the route knows*, not to second-guess
which combination the product accepts.

    backend/.venv/bin/python scripts/gen_documented_bodies.py
"""

from __future__ import annotations

import json
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SWAGGER = ROOT / "data" / "swagger_2_1.json"
OUT = ROOT / "backend" / "application" / "documented_bodies.py"
PREFIX = "/web/api/v2.1"

_MAX_DEPTH = 8


def resolve(schema: dict, definitions: dict, depth: int = 0) -> dict:
    """Follow a `$ref` to the definition it names."""
    if depth > _MAX_DEPTH or not isinstance(schema, dict):
        return {}
    ref = schema.get("$ref")
    if ref:
        return resolve(definitions.get(ref.split("/")[-1], {}), definitions, depth + 1)
    return schema


def member_names(schema: dict, definitions: dict) -> set[str]:
    """The members that make a body recognisable as one.

    The top-level ones, plus the members of the `data` payload — the flat
    form of the same document, which the mock takes as well.
    """
    resolved = resolve(schema, definitions)
    properties = resolved.get("properties") or {}
    names = set(properties)
    payload = resolve(properties.get("data", {}), definitions)
    # `data` is a list on the routes that create several records at once —
    # the flat form of those is one of its items, not the list.
    if payload.get("type") == "array":
        payload = resolve(payload.get("items", {}), definitions)
    names |= set(payload.get("properties") or {})
    return names


def main() -> int:
    """Write the documented body members for every SentinelOne write route."""
    if not SWAGGER.exists():
        print(f"missing {SWAGGER} — run scripts/fetch_swagger.sh first")
        return 2
    swagger = json.loads(SWAGGER.read_text())
    definitions = swagger.get("definitions", {})

    rows: list[tuple[str, str, list[str], list[str]]] = []
    for path, operations in sorted(swagger.get("paths", {}).items()):
        if not path.startswith(PREFIX):
            continue
        for verb in ("post", "put"):
            operation = operations.get(verb)
            if not operation:
                continue
            bodies = [
                p for p in operation.get("parameters", []) if p.get("in") == "body"
            ]
            if not bodies:
                continue
            schema = bodies[0].get("schema", {})
            required = sorted(resolve(schema, definitions).get("required", []) or [])
            if not required:
                continue
            # Keyed without the API prefix, the way the router sees it —
            # `documented_filters.py` keys the same way.
            rows.append((verb.upper(), path[len(PREFIX):] or "/", required,
                         sorted(member_names(schema, definitions))))

    lines = [
        '"""What each SentinelOne write body must carry, from the 2.1 swagger.',
        "",
        "Generated by scripts/gen_documented_bodies.py — do not edit by hand.",
        "",
        "A route that answers 200 to a body carrying none of these members is",
        "accepting a body the vendor's own reference says is not one. The mock",
        "also takes the flat form of these payloads, so `data`'s own members",
        "count as having been sent too.",
        '"""',
        "from __future__ import annotations",
        "",
        "#: ``(method, route path)`` → every member the swagger documents for",
        "#: that body. The path is the one the router carries — no API prefix.",
        "DOCUMENTED_BODIES: dict[tuple[str, str], frozenset[str]] = {",
    ]
    for verb, path, _required, members in rows:
        key = f'    ("{verb}", "{path}"): frozenset({{'
        if len(key) > 100:
            lines.append('    (')
            lines.append(f'        "{verb}", "{path}",')
            lines.append("    ): frozenset({")
        else:
            lines.append(key)
        names = ", ".join(f'"{m}"' for m in members)
        lines += textwrap.wrap(names, width=74,
                               initial_indent=" " * 8, subsequent_indent=" " * 8)
        lines.append("    }),")
    lines.append("}")
    lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"{len(rows)} route(s) → {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
